### PR TITLE
Fix unenclosed items

### LINKED ISSUE #229: Issue parsing feed items without enclosure
The [episode picker](https://github.com/PRX/play.prx.org/blob/master/src/app/builder/episode/episode-picker.component.ts#L85) assumes there will always be an enclosure (and some other elements)

### PR DESCRIPTION
**Pull request by kookster**
Fixes #229 

- [x] Make the player work when items in the feed have no enclosure
- [x] Make the player render even if a specific item has no audio - the player won't play of course, but render title and such.

### CODE REVIEW

File: src/app/builder/episode/episode-picker.component.ts [hunk 1]
```diff
@@ -82,7 +82,11 @@ export class EpisodePickerComponent implements OnChanges, OnInit {
           return txt.value;
         }(item.querySelector('title').innerHTML);
 
-        let encUrl = item.querySelector('enclosure').getAttribute('url');
+        let encUrl = null;
```
Comment (kookster) [inline src/app/builder/episode/episode-picker.component.ts:85]: This handles when there is no enclosure in the feed, so there is no error in the parsing.

File: src/app/embed/adapters/feed.adapter.ts [hunk 2]
```diff
@@ -132,7 +132,7 @@ export class FeedAdapter implements DataAdapter {
   processEpisode(item: Element, props: AdapterProperties = {}): AdapterProperties {
     props.title = this.getTagText(item, 'title');
     props.audioUrl = this.getTagTextNS(item, FEEDBURNER_NAMESPACE, 'origEnclosureLink')
-                  || this.getTagAttribute(item, 'enclosure', 'url');
+                  || this.getTagAttribute(item, 'enclosure', 'url') || null;
```
Comment (kookster) [inline src/app/embed/adapters/feed.adapter.ts:135]: This handles the case when the player is set on an episode in the feed that has no audio.
At least now renders the rest of the player, rather then all gray.

File: src/app/embed/share/share-modal.component.ts [hunk 3]
```diff
@@ -5,7 +5,7 @@ import { Component, EventEmitter, Output, Input } from '@angular/core';
   styleUrls: ['share-modal.component.css'],
   template: `
     <button class="close-btn" (click)="closeModal()" (window:keydown)="handleKeypress($event)">✖</button>
-    <template [ngIf]="mode == 'share'">
+    <ng-template [ngIf]="mode == 'share'">
```
Comment (kookster) [inline src/app/embed/share/share-modal.component.ts:8]: this is an angular change, `<template/>` is too generic, so they use `<ng-template/>`

File: src/styles.css [hunk 4]
```diff
@@ -1,12 +1,12 @@
 /*
  * Global styles manifest
  */
+@import url(https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css);
```
Comment (kookster) [inline src/styles.css:4]: Imports should come first

**Review by sandikbarr — APPROVED** [review]
👍 looks good
